### ISSUE TITLE
Renombrar repositorio

### ISSUE THREAD

**Issue by vcuspinera** [edurios2021/edurios.github.io#1]
Hola @edurios2021 tu repositorio se debería llamar "**edurios2021.github.io**".

Saludos,  
Víctor

**Comment by edurios2021** [comment]
Una disculpa Dr. @vcuspinera, se me paso agregar el "2021". Gracias por la aclaración.
Ya se renombre el repositorio al correcto.
Quedo atento a sus comentarios

**Comment by vcuspinera** [comment]
Sobre todo es para que se vea tu página Eduardo. Saludos

**Comment by edurios2021** [comment]
Perfecto.
Una duda Dr. ¿se va a modificar mi calificación de la actividad 13 que realizamos?
Me parece que tengo un "0" y es por el tema de renombramiento del repositorio.
Quedo en la espera de su comentario.
Saludos y gracias

**Comment by vcuspinera** [comment]
Sí se va a cambiar la calificación Eduardo, sólo que hago las actualizaciones de califs 1 o 2 veces por semana.

**Comment by edurios2021** [comment]
Enterado Dr.
Gracias por la retroalimentación
Saludos!
